/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void testMonsterInitialization() {
    Monster monster = new Monster(0, 1);

    assertEquals("スライム", monster.name);
    assertEquals(1, monster.rare);
  }

  @Test
  public void testSummonMonster() {
    Monster monster = new Monster(2, 1);

    assertEquals("ドラゴン", monster.name);
  }

  @Test
  public void testToString() {
    Monster monster = new Monster(3, 2);

    assertEquals("デュラハン:レア度[2]", monster.toString());
  }

  @Test
  public void testEvolveMonster() {
    Monster monster = new Monster(1, 3);

    assertEquals("サハギン（進化）", monster.name);
  }
}
