/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.LinkedList;
import org.junit.Test;
import static org.junit.Assert.*;

public class SeMonsterGameTest {
    @Test
    public void testAddPlayer() {
        LinkedList<Integer> rndNumList = new LinkedList<>();
        for (int i = 0; i < 8; i++) {
            rndNumList.add(i % 5);
            rndNumList.add((i+2) % 5);
        }
        SeMonsterGame game = new SeMonsterGame(rndNumList);
        game.addPlayer("TestPlayer");

        Player result = game.playerMap.get("TestPlayer");

        assertNotNull(result);
        assertEquals("TestPlayer", result.name);
    }

    @Test
    public void testDraw() {
        LinkedList<Integer> rndNumList = new LinkedList<>();
        for (int i = 0; i < 8; i++) {
            rndNumList.add(i % 5);
            rndNumList.add((i+2) % 5);
        }
        SeMonsterGame game = new SeMonsterGame(rndNumList);
        game.addPlayer("TestPlayer");

        game.draw("TestPlayer");
        Player result = game.playerMap.get("TestPlayer");

        assertNotNull(result);
        assertEquals(8, result.deck.size());
    }
}
