/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

public class PlayerTest {
  @Test
  public void testMonster() {
    int name = 3;
    int rare = 0;
    String monsters[] = { "スライム", "サハギン", "ドラゴン", "デュラハン", "シーサーペント" };

    Monster monster = new Monster(name, rare);
    assertEquals(monsters[name] + ":レア度[" + rare + "]", monster.toString());

    int a = 1;
    assertEquals("サハギン", monster.summonMonster(a));
  }

}

