/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

public class PlayerTest {
  @Test
  public void testPlayer() {
    int name;
    int rare;
    String playerName = "user";
    String monsters[] = { "スライム", "サハギン", "ドラゴン", "デュラハン", "シーサーペント" };
    int rndnum[] = {0,1,2,1,4};

    Player player = new Player(rndnum, playerName);
    assertEquals(monsters[name] + ":レア度[" + rare + "]", monster.toString());

    int a = 1;
    assertEquals("サハギン", monster.summonMonster(a));
  }

}

